version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/compiler"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "webcien"
    labels:
      - "dependencies"
